import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Shital",
      email: "admin@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "John",
      email: "user@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Free Shirt",
      slug: "free-shirt",
      image: "/images/shirt1.jpg",
      banner: "/images/banner1.jpg",
      price: 70,
      brand: "Nike",
      description: "A popular shirt",
      category: "Shirts",
      rating: 4.5,
      numReviews: 9,
      countInStock: 20,
      isFeatured: true,
    },
    {
      name: "Fit Shirt",
      slug: "fit-shirt",
      image: "/images/shirt2.jpg",
      banner: "/images/banner2.jpg",
      price: 80,
      brand: "Adidas",
      description: "A popular fit shirt",
      category: "Shirts",
      rating: 4.2,
      numReviews: 19,
      countInStock: 30,
    },
    {
      name: "Slim Shirt",
      slug: "slim-shirt",
      image: "/images/shirt3.jpg",
      banner: "/images/banner3.jpg",
      price: 100,
      brand: "Raymond",
      description: "A popular slim shirt",
      category: "Shirts",
      rating: 4.7,
      numReviews: 21,
      countInStock: 18,
    },
    {
      name: "Golf Pants",
      slug: "golf-pants",
      image: "/images/golfpant.jpg",
      banner: "/images/banner4.jpg",
      price: 120,
      brand: "Oliver",
      description: "A popular golf pant",
      category: "Pants",
      rating: 4.6,
      numReviews: 25,
      countInStock: 35,
    },
    {
      name: "Fit Pants",
      slug: "fit-pants",
      image: "/images/fitpant.jpg",
      banner: "/images/banner5.jpg",
      price: 130,
      brand: "Zara",
      description: "A popular fit pant",
      category: "Pants",
      rating: 4.7,
      numReviews: 23,
      countInStock: 20,
    },
    {
      name: "Classic Pants",
      slug: "classsic-pants",
      image: "/images/classicpant.jpg",
      banner: "/images/banner6.jpg",
      price: 125,
      brand: "Casely",
      description: "A popular fit pant",
      category: "Pants",
      rating: 4.4,
      numReviews: 17,
      countInStock: 30,
    },
  ],
};

export default data;
